base_images:
  base:
    name: "4.15"
    namespace: ocp
    tag: cli
  ocp_builder_rhel-8-golang-1.20-openshift-4.15:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.20-openshift-4.15
build_root:
  from_repository: true
images:
- dockerfile_literal: |
    FROM registry.ci.openshift.org/openshift/fedora:latest
    WORKDIR /home/jenkins
    COPY . .
    USER 0
    RUN dnf install -y device-mapper-devel btrfs-progs-devel git golang make && dnf clean all
  to: jenkins-test-runner
- context_dir: "2"
  dockerfile_path: Dockerfile.rhel8
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.20-openshift-4.15:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/2/.
  to: jenkins
- context_dir: slave-base
  dockerfile_path: Dockerfile.rhel8
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.20-openshift-4.15:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/slave-base/.
  to: jenkins-agent-base
promotion:
  excluded_images:
  - jenkins-test-runner
  name: "4.15"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.15"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.15"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: jenkins-check-plugins-supply-chain-change
  commands: hack/check-plugins-supply-chain-change.sh
  container:
    clone: true
    from: ocp_builder_rhel-8-golang-1.20-openshift-4.15
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: e2e-jenkins-image-tests
  commands: IMAGE_NAME=stable:jenkins make smoke
  container:
    clone: true
    from: ocp_builder_rhel-8-golang-1.20-openshift-4.15
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: e2e-aws-jenkins
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: make e2e
      dependencies:
      - env: JENKINS_IMAGE
        name: pipeline:jenkins
      - env: JENKINS_AGENT_BASE_IMAGE
        name: pipeline:jenkins-agent-base
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
- as: security
  optional: true
  steps:
    env:
      PROJECT_NAME: ocptools-jenkins
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: master
  org: openshift
  repo: jenkins
