base_images:
  base:
    name: "4.14"
    namespace: ocp
    tag: cli
  ocp_builder_rhel-8-golang-1.19-openshift-4.13:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.19-openshift-4.13
build_root:
  from_repository: true
images:
  - context_dir: "2"
    dockerfile_path: Dockerfile.rhel8
    from: base
    inputs:
      ocp_builder_rhel-8-golang-1.19-openshift-4.13:
        as:
          - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13
      src:
        paths:
          - destination_dir: .
            source_path: /go/src/github.com/openshift/jenkins/2/.
    to: jenkins
  - context_dir: slave-base
    dockerfile_path: Dockerfile.rhel8
    from: base
    inputs:
      ocp_builder_rhel-8-golang-1.19-openshift-4.13:
        as:
          - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13
      src:
        paths:
          - destination_dir: .
            source_path: /go/src/github.com/openshift/jenkins/slave-base/.
    to: jenkins-agent-base
promotion:
  name: "4.14"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
  openshift-4-11:
    integration:
      name: "4.11"
      namespace: ocp
  openshift-4-12:
    integration:
      name: "4.12"
      namespace: ocp
  openshift-4-13:
    integration:
      name: "4.13"
      namespace: ocp
resources:
  "*":
    requests:
      cpu: 100m
      memory: 200Mi
tests:
  - as: e2e-aws
    skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
    steps:
      cluster_profile: aws
      workflow: openshift-e2e-aws
  - as: e2e-aws-4-13
    skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
    steps:
      dependencies:
        OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
        RELEASE_IMAGE_LATEST: release:openshift-4-13
      cluster_profile: aws
      workflow: openshift-e2e-aws

zz_generated_metadata:
  branch: master
  org: openshift
  repo: jenkins
